---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: NodePort
  ports:
    - port: 8086
      protocol: TCP
  selector:
    app: influxdb
---
apiVersion: v1
kind: Pod
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  containers:
  - name: influxdb
    image: influxdb:1.8.3-alpine
    env:
      - name: INFLUXDB_DB
        value: k6
    ports:
      - name: web
        containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: datasource-config
data:
  grafana-datasource.yaml: |
    apiVersion: 1
    datasources:
        - name: k6influxdb
          type: influxdb
          access: proxy
          database: k6
          url: http://influxdb:8086
          isDefault: true
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
  - name: grafana
    image: grafana/grafana:7.3.1
    env:
      - name: GF_AUTH_ANONYMOUS_ORG_ROLE
        value: Admin
      - name: GF_AUTH_ANONYMOUS_ENABLED
        value: "true"
      - name: GF_AUTH_BASIC_ENABLED
        value: "false"
    ports:
      - name: web
        containerPort: 3000
    volumeMounts:
        - name: datasource-vol
          mountPath: /etc/grafana/provisioning/datasources/
          readOnly: true
  volumes:
    - name: datasource-vol
      configMap:
        name: datasource-config
        items:
          - key: "grafana-datasource.yaml"
            path: "datasource.yaml"