apiVersion : apps/v1
kind: Deployment
metadata:
  name: "k6-8977"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "k6-8977"
  template:
    metadata:
      labels:
        app: "k6-8977"
    spec:
      containers:
        - name: "k6-8977"
          image: "k6reg.azurecr.io/k6"
          ports:
          - containerPort: 80