apiVersion: v1
kind: Service
metadata:
    name: "k6-8977"
    labels:
        app: "k6-8977"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k6-8977"