on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: k6reg.azurecr.io
        username: ${{ secrets.acr_k6reg_username }}
        password: ${{ secrets.acr_k6reg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t k6reg.azurecr.io/k6:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push k6reg.azurecr.io/k6:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k6_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k6b433 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k6b433`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k6b433
        container-registry-url: k6reg.azurecr.io
        container-registry-username: ${{ secrets.acr_k6reg_username }}
        container-registry-password: ${{ secrets.acr_k6reg_password }}
        secret-name: k6dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k6b433
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          k6reg.azurecr.io/k6:${{ github.sha }}
        imagepullsecrets: |
          k6dockerauth
